pipeline {
    agent any

    stages {

        stage('Install dependencies') {
            steps {
                sh 'pip3 install -r requirements.txt'
            }
        }

        stage('Run tests') {
            steps {
                sh 'python3 -m pytest --junitxml=result.xml'
            }
        }
    }

    post {
        always {
            junit 'result.xml'
        }
    }
}